#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define SD_CARD_MOUNT_POINT "/sdcard"
#define SD_CARD_MMC_PIN_CMD GPIO_NUM_NC
#define SD_CARD_MMC_PIN_CLK GPIO_NUM_NC
#define SD_CARD_MMC_PIN_D0 GPIO_NUM_NC

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_16
#define AUDIO_I2S_GPIO_WS GPIO_NUM_4
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_7
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_6

#define AUDIO_CODEC_USE_PCA9557
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_5
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_3
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  0x82

#define BUILTIN_LED_GPIO        GPIO_NUM_48
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_10
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_39
#define PA_ENABLE_GPIO          GPIO_NUM_17

#define DISPLAY_WIDTH   320
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY true

#define DISPLAY_WIDTH_1  240 
#define DISPLAY_HEIGHT_1  320 
#define DISPLAY_MIRROR_X_1 false
#define DISPLAY_MIRROR_Y_1 false 
#define DISPLAY_SWAP_XY_1 false 

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_42
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define DISPLAY_MOSI_PIN      GPIO_NUM_47
#define DISPLAY_CLK_PIN       GPIO_NUM_21
#define DISPLAY_DC_PIN        GPIO_NUM_40
#define DISPLAY_RST_PIN       GPIO_NUM_45
#define DISPLAY_CS_PIN        GPIO_NUM_41


/* Camera pins */
#define CAMERA_PIN_PWDN -1
#define CAMERA_PIN_RESET -1
#define CAMERA_PIN_XCLK -1
#define CAMERA_PIN_SIOD -1
#define CAMERA_PIN_SIOC -1

#define CAMERA_PIN_D7 -1
#define CAMERA_PIN_D6 -1
#define CAMERA_PIN_D5 -1
#define CAMERA_PIN_D4 -1
#define CAMERA_PIN_D3 -1
#define CAMERA_PIN_D2 -1
#define CAMERA_PIN_D1 -1
#define CAMERA_PIN_D0 -1
#define CAMERA_PIN_VSYNC -1
#define CAMERA_PIN_HREF -1
#define CAMERA_PIN_PCLK -1

#define XCLK_FREQ_HZ 24000000

#endif // _BOARD_CONFIG_H_
